name: CI

on:
  - pull_request
  - push
  
jobs:
  tests:
      name: Tests

      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install PHP with extensions
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.0
            coverage: xdebug3
            tools: none
            
        - name: Install dependencies with composer
          run: php ./tools/composer update --no-ansi --no-interaction --no-progress
          
          
        - name: Run tests with phpunit/phpunit
          run: vendor/bin/phpunit --coverage-clover=coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
